name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["metrics"]}
jobs:
  achievements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: DungGramer
          template: classic
          base: ""
          config_timezone: Asia/Saigon
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_limit: 7
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

  followers:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.followers.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: DungGramer
          template: classic
          base: ""
          config_timezone: Asia/Saigon
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers

  habit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.habit.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: DungGramer
          template: classic
          base: ""
          config_timezone: Asia/Saigon
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200